version: '3.8'
services:
        ebook:
             build: .
             container_name: do-s2-cloud-computing
             image: registry.mejik.xyz/ebook/do-s2-cloud-computing
             ports:
                     - 3038:3000
